services:
  db: 
    image: mysql:5.7
    container_name: project-database-mystica
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./repository/createDatabase.sql:/docker-entrypoint-initdb.d/Database.sql